/* TODO: delete this file after connecting to the api */

export const products = [
  {
    id: 1,
    title: 'Apple iPhone Xs 64GB Silver (iMT9G2FS/A)',
    price: 799,
    oldPrice: 899,
    display: '5.8" OLED',
    capacity: '64GB',
    ram: '4GB',
    imageSrc: '/img/phones/apple-iphone-xs/gold/00.webp',
  },
  {
    id: 2,
    title: 'Apple iPhone 13 128GB Midnight',
    price: 999,
    oldPrice: 1099,
    display: '6.1" OLED',
    capacity: '128GB',
    ram: '6GB',
    imageSrc: '/img/phones/apple-iphone-13-mini/midnight/00.webp',
  },
  {
    id: 3,
    title: 'Apple iPhone Xs 64GB Silver (iMT9G2FS/A)',
    price: 799,
    oldPrice: 899,
    display: '5.8" OLED',
    capacity: '64GB',
    ram: '4GB',
    imageSrc: '/img/phones/apple-iphone-xs/gold/00.webp',
  },
  {
    id: 4,
    title: 'Apple iPhone 13 128GB Midnight',
    price: 999,
    oldPrice: 1099,
    display: '6.1" OLED',
    capacity: '128GB',
    ram: '6GB',
    imageSrc: '/img/phones/apple-iphone-13-mini/midnight/00.webp',
  },
  {
    id: 5,
    title: 'Apple iPhone 13 128GB Midnight',
    price: 999,
    oldPrice: 1099,
    display: '6.1" OLED',
    capacity: '128GB',
    ram: '6GB',
    imageSrc: '/img/phones/apple-iphone-13-mini/midnight/00.webp',
  },
  {
    id: 6,
    title: 'Apple iPhone 13 128GB Midnight',
    price: 999,
    oldPrice: 1099,
    display: '6.1" OLED',
    capacity: '128GB',
    ram: '6GB',
    imageSrc: '/img/phones/apple-iphone-13-mini/midnight/00.webp',
  },
  {
    id: 7,
    title: 'Apple iPhone 13 128GB Midnight',
    price: 999,
    oldPrice: 1099,
    display: '6.1" OLED',
    capacity: '128GB',
    ram: '6GB',
    imageSrc: '/img/phones/apple-iphone-13-mini/midnight/00.webp',
  },
  {
    id: 8,
    title: 'Apple iPhone 13 128GB Midnight',
    price: 999,
    oldPrice: 1099,
    display: '6.1" OLED',
    capacity: '128GB',
    ram: '6GB',
    imageSrc: '/img/phones/apple-iphone-13-mini/midnight/00.webp',
  },
];
